spring:
  application:
    name: dubbo-service-provider
dubbo:
  scan:
    base-packages: io.futakotome
  protocol:
    port: -1
    name: dubbo
  registry:
    address: zookeeper://${zookeeper.server.host}:${zookeeper.server.port}/?registry-type=service

zookeeper:
  server:
    host: 127.0.0.1
    port: 2181