multiple:
  mysql:
    enabled: false
  redis:
    enabled: true
    connections:
      - key: redis-1
        host: localhost
        port: 6379
        clientName: redis-client-1
        password: admin
        database: 0
        lettuce:
          pool:
            max-active: 8
            maxIdle: 8
            minIdle: 1
        timeout: 6000
  mongo:
    enabled: false

logging:
  level:
    root: info